Remove Bash scripts

diff --git a/.github/workflows/lint-bash.yml b/.github/workflows/lint-bash.yml
--- a/.github/workflows/lint-bash.yml
+++ b/.github/workflows/lint-bash.yml
@@ -42,10 +42,64 @@ jobs:
           shopt -u globstar nullglob
 
       - name: Check Bash Scripts for "#!/bin/bash"
-        run: .github/workflows/helpers/check_shebang.sh
+        run: |
+          while read -r file
+          do
+            if [[ "$(head -c 11 "$file")" = "#!/bin/bash" ]]
+            then
+              echo "[#!/bin/bash -> Present] $file"
+            else
+              echo "[#!/bin/bash -> NOT FOUND] $file" && exit 1
+            fi
+          done < <(find . -name '*.sh')
 
       - name: Check Bash Scripts for "set -Eeuo pipefail"
-        run: .github/workflows/helpers/check_pipefail.sh
+        run: |
+          while read -r file
+          do
+            if grep -q \
+              -e "^set -Eeuo pipefail$" \
+              -e "^# @paradedb-skip-check-pipefail$" \
+              "$file"
+            then
+              echo "[set -Eeuo pipefail -> Present] $file"
+            else
+              echo "[set -Eeuo pipefail -> NOT FOUND] $file" && exit 1
+            fi
 
       - name: Run ShellCheck
-        run: python3 .github/workflows/helpers/check_shellcheck.py
+        shell: python {0}
+        run: |
+          # Obtain list of all .sh files after excluding directories
+          sh_files = set(glob.glob("**/*.sh", recursive=True))
+          for dir_path in exclude_dirs:
+              sh_files -= set(glob.glob(f"{dir_path}**/*.sh", recursive=True))
+
+          codes_to_exclude = {}
+          exclude_codes = args.exclude_codes.split()
+          for code in exclude_codes:
+              filename, codes = code.split(":")
+              codes_to_exclude[filename] = codes
+
+          for file in sh_files:
+              if file not in codes_to_exclude:
+                  p = subprocess.run(
+                      f"shellcheck {file}", shell=True, capture_output=True, check=False
+                  )
+                  print(p.stdout.decode())
+                  if p.returncode != 0:
+                      print(f"[Shellcheck did not pass] {file}")
+                      sys.exit(1)
+              else:
+                  codes = codes_to_exclude[file]
+                  p = subprocess.run(
+                      f"shellcheck -e {codes} {file}",
+                      shell=True,
+                      capture_output=True,
+                      check=False,
+                  )
+                  print(p.stdout.decode())
+                  if p.returncode != 0:
+                      print(f"[Shellcheck did not pass] {file}")
+                      sys.exit(1)
+              print(f"[Shellcheck passed] {file}")
