Add support for publishing beta versions

diff --git a/.github/workflows/publish-github-release.yml b/.github/workflows/publish-github-release.yml
--- a/.github/workflows/publish-github-release.yml
+++ b/.github/workflows/publish-github-release.yml
@@ -1,7 +1,8 @@
 # workflows/publish-github-release.yml
 #
 # Publish GitHub Release
-# Publish the ParadeDB GitHub Release.
+# Publish the ParadeDB GitHub Release. Pushes to `main` publish an official release while
+# pushes to `staging` publish a beta release.
 
 name: Publish GitHub Release
 
@@ -9,7 +10,7 @@ on:
   push:
     branches:
       - main
-      - dev
+      - staging
   workflow_dispatch:
 
 concurrency:
@@ -31,9 +32,12 @@ jobs:
           if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
             echo "environment=prod" >> $GITHUB_OUTPUT
             echo "Using prod configuration..."
+          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
+            echo "environment=staging" >> $GITHUB_OUTPUT
+            echo "Using staging configuration..."
           else
-            echo "environment=dev" >> $GITHUB_OUTPUT
-            echo "Using dev configuration..."
+            echo "Invalid environment. Exiting..."
+            exit 1
           fi
 
       # We store the GitHub Release version number in GitHub Actions Variables. Since it's
@@ -50,15 +54,16 @@ jobs:
             # Increment GHA variable version by 0.0.1 for next release
             GHA_VAR_NAME="VERSION_PATCH"
             GHA_VAR_VALUE="$(( ${{ vars.VERSION_PATCH }} + 1 ))"
-          elif [[ "${{ steps.env.outputs.environment }}" == "dev" ]]; then
-            echo 'Using dev configuration...'
-            CURRENT_RELEASE_VERSION="${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.${{ vars.VERSION_PATCH }}-dev-rc.${{ vars.VERSION_DEV_RC }}"
+          elif [[ "${{ steps.env.outputs.environment }}" == "staging" ]]; then
+            echo 'Using staging configuration...'
+            CURRENT_RELEASE_VERSION="${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.${{ vars.VERSION_PATCH }}-rc.${{ vars.VERSION_RC }}"
 
-            # Increment GHA variable version by dev-rc.1 for next release
+            # Increment GHA variable version by -rc.1 for next release
             GHA_VAR_NAME="VERSION_DEV_RC"
-            GHA_VAR_VALUE="$(( ${{ vars.VERSION_DEV_RC }} + 1 ))"
+            GHA_VAR_VALUE="$(( ${{ vars.VERSION_RC }} + 1 ))"
           else
-            echo "Error: Invalid branch" && false
+            echo "Error: Invalid branch, exiting..."
+            exit 1
           fi
 
           # Output the current release version to create the GitHub Release tag, and the new version to update GitHub Actions variable
@@ -84,11 +89,11 @@ jobs:
               --method PATCH \
               -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
-              /repos/paradedb/paradedb/actions/variables/VERSION_DEV_RC \
-              -f name='VERSION_DEV_RC' \
+              /repos/paradedb/paradedb/actions/variables/VERSION_RC \
+              -f name='VERSION_RC' \
               -f value='0'
-          # on dev we only update dev RC
-          elif [[ "${{ steps.env.outputs.environment }}" == "dev" ]]; then
+          # on staging we only update RC
+          elif [[ "${{ steps.env.outputs.environment }}" == "staging" ]]; then
             gh api \
               --method PATCH \
               -H "Accept: application/vnd.github+json" \
@@ -101,7 +106,6 @@ jobs:
           fi
 
       - name: Create GitHub Release (prod only)
-        if: steps.env.outputs.environment == 'prod'
         uses: softprops/action-gh-release@v2
         with:
           tag_name: v${{ steps.version.outputs.version }}
