Undo testing, works

diff --git a/.github/workflows/publish-github-release.yml b/.github/workflows/publish-github-release.yml
--- a/.github/workflows/publish-github-release.yml
+++ b/.github/workflows/publish-github-release.yml
@@ -11,7 +11,6 @@ on:
     branches:
       - main
       - staging
-      - phil/release-0.15.25
   workflow_dispatch:
 
 concurrency:
@@ -50,7 +49,7 @@ jobs:
             GHA_VAR_VALUE="$(( ${{ vars.VERSION_RC }} + 1 ))"
           else
             echo "Error: Invalid branch, exiting..."
-            # exit 1
+            exit 1
           fi
 
           # Output the current release version to create the GitHub Release tag, and the new version to update GitHub Actions variable
@@ -58,39 +57,39 @@ jobs:
           echo "gha_var_name=${GHA_VAR_NAME}" >> $GITHUB_OUTPUT
           echo "gha_var_value=${GHA_VAR_VALUE}" >> $GITHUB_OUTPUT
 
-      # - name: Update Version Number in GitHub Actions Variables
-      #   env:
-      #     GH_TOKEN: ${{ secrets.GHA_CREATE_RELEASE_PAT }}
-      #   run: |
-      #     # On `main` we update patch and reset the RC version to 1
-      #     if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
-      #       gh api \
-      #         --method PATCH \
-      #         -H "Accept: application/vnd.github+json" \
-      #         -H "X-GitHub-Api-Version: 2022-11-28" \
-      #         /repos/paradedb/paradedb/actions/variables/${{ steps.version.outputs.gha_var_name }} \
-      #         -f name='${{ steps.version.outputs.gha_var_name }}' \
-      #         -f value='${{ steps.version.outputs.gha_var_value }}'
+      - name: Update Version Number in GitHub Actions Variables
+        env:
+          GH_TOKEN: ${{ secrets.GHA_CREATE_RELEASE_PAT }}
+        run: |
+          # On `main` we update patch and reset the RC version to 1
+          if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
+            gh api \
+              --method PATCH \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              /repos/paradedb/paradedb/actions/variables/${{ steps.version.outputs.gha_var_name }} \
+              -f name='${{ steps.version.outputs.gha_var_name }}' \
+              -f value='${{ steps.version.outputs.gha_var_value }}'
 
-      #       gh api \
-      #         --method PATCH \
-      #         -H "Accept: application/vnd.github+json" \
-      #         -H "X-GitHub-Api-Version: 2022-11-28" \
-      #         /repos/paradedb/paradedb/actions/variables/VERSION_RC \
-      #         -f name='VERSION_RC' \
-      #         -f value='1'
-      #     # On `staging` we only update the RC version
-      #     elif [[ ${{ github.ref }} == "refs/heads/staging" ]]; then
-      #       gh api \
-      #         --method PATCH \
-      #         -H "Accept: application/vnd.github+json" \
-      #         -H "X-GitHub-Api-Version: 2022-11-28" \
-      #         /repos/paradedb/paradedb/actions/variables/${{ steps.version.outputs.gha_var_name }} \
-      #         -f name='${{ steps.version.outputs.gha_var_name }}' \
-      #         -f value='${{ steps.version.outputs.gha_var_value }}'
-      #     else
-      #       echo "Error: Invalid branch" && false
-      #     fi
+            gh api \
+              --method PATCH \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              /repos/paradedb/paradedb/actions/variables/VERSION_RC \
+              -f name='VERSION_RC' \
+              -f value='1'
+          # On `staging` we only update the RC version
+          elif [[ ${{ github.ref }} == "refs/heads/staging" ]]; then
+            gh api \
+              --method PATCH \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              /repos/paradedb/paradedb/actions/variables/${{ steps.version.outputs.gha_var_name }} \
+              -f name='${{ steps.version.outputs.gha_var_name }}' \
+              -f value='${{ steps.version.outputs.gha_var_value }}'
+          else
+            echo "Error: Invalid branch" && false
+          fi
 
       # The tag_name will have `-rc.X` suffix and be marked as a prerelease for staging releases,
       # and no suffix and marked as a full release for prod releases
@@ -100,6 +99,6 @@ jobs:
           tag_name: v${{ steps.version.outputs.version }}
           target_commitish: "main"
           generate_release_notes: true
-          prerelease: true
+          prerelease: ${{ github.ref == 'refs/heads/staging' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GHA_CREATE_RELEASE_PAT }}
