parse output in pgrx regress

diff --git a/.github/workflows/test-pg_search.yml b/.github/workflows/test-pg_search.yml
--- a/.github/workflows/test-pg_search.yml
+++ b/.github/workflows/test-pg_search.yml
@@ -153,9 +153,13 @@ jobs:
 
       - name: Run pg_search Regression Tests Against distro-managed Postgres
         run: |
-          cargo pgrx regress --package pg_search pg${{ matrix.pg_version }} --features=icu
-          if [ $? -ne 0 ]; then
-            exit 1
+          output=$(cargo pgrx regress --package pg_search pg${{ matrix.pg_version }} --features=icu)
+          echo "$output"
+          if echo "$output" | grep -q "failed="; then
+            failed_count=$(echo "$output" | grep -o "failed=[0-9]*" | cut -d'=' -f2)
+            if [ "$failed_count" -gt 0 ]; then
+              exit 1
+            fi
           fi
 
       - name: Print the Postgres Logs
