ci: Add test for whether the Dockerfile starts properly (#1068)

diff --git a/.github/workflows/test-paradedb.yml b/.github/workflows/test-paradedb.yml
--- a/.github/workflows/test-paradedb.yml
+++ b/.github/workflows/test-paradedb.yml
@@ -34,6 +34,16 @@ jobs:
         uses: actions/checkout@v4
 
       # By using the docker-compose.dev.yml file, we also test that the build arguments are correct
-      - name: Test Building ParadeDB Docker Image
+      - name: Build the ParadeDB Docker Image
         working-directory: docker/
         run: docker buildx create --use && docker compose -f docker-compose.dev.yml build
+
+      # Sleep 10 seconds to give time for Postgres to start inside the container
+      - name: Start the ParadeDB Docker Image
+        working-directory: docker/
+        run: docker compose -f docker-compose.dev.yml up -d && sleep 10
+
+      # We run the container in detached mode, and grep for the word ERROR to see if it failed to start correctly
+      - name: Check for Errors in the ParadeDB Docker Image
+        working-directory: docker/
+        run: docker logs $(docker ps -q --filter "name=paradedb-dev") | grep -q ERROR || exit 0
