big overhaul to pg_bm25 test

diff --git a/.github/workflows/test-pg_bm25.yml b/.github/workflows/test-pg_bm25.yml
--- a/.github/workflows/test-pg_bm25.yml
+++ b/.github/workflows/test-pg_bm25.yml
@@ -23,12 +23,17 @@ concurrency:
 
 jobs:
   test-pg_bm25:
-    name: Test pg_bm25
+    name: Test pg_bm25 on PostgreSQL ${{ matrix.pg_version }}
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        pg_version: [11, 12, 13, 14, 15]
 
     steps:
-      - name: Checkout Git Repository
+      - name: Sparse Checkout Git Repository
         uses: actions/checkout@v4
+        with:
+          path: pg_bm25
 
       - name: Cache Cargo Dependencies
         uses: actions/cache@v3
@@ -39,59 +44,40 @@ jobs:
             ~/.cargo/bin/
             ~/.rustup/
             pg_bm25/target
-          key: ${{ runner.os }}-cargo-${{ hashFiles('pg_bm25/Cargo.lock') }}
+          key: ${{ runner.os }}-cargo-${{ hashFiles('pg_bm25/Cargo.lock') }}xw
 
-      - name: Install All Supported PostgreSQL Versions
+      - name: Cache PostgreSQL Binaries
+        id: cache-pg
+        uses: actions/cache@v3
+        with:
+          path: /usr/share/postgresql/
+          key: ${{ runner.os }}-postgresql-${{ matrix.pg_version }}
+
+      - name: Install Supported PostgreSQL Version
+        if: steps.cache-pg.outputs.cache-hit != 'true'
         run: |
-          # Install the public key for the repository
           wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
-          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
-
-          # Install PostgreSQL 11, 12, 13, 14, and 15
-          sudo apt-get update
-          sudo apt-get install -y postgresql-11 postgresql-12 postgresql-13 postgresql-14 postgresql-15
-          sudo apt-get install -y postgresql-server-dev-11 postgresql-server-dev-12 postgresql-server-dev-13 postgresql-server-dev-14 postgresql-server-dev-15
+          echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
+          sudo apt-get update && sudo apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}
 
       - name: Configure PostgreSQL Directories
         run: |
-          # Set the required permissions for unit tests to run in GitHub Actions
-          sudo chown -R $(whoami) /usr/share/postgresql/11/extension/ /usr/lib/postgresql/11/lib/
-          sudo chown -R $(whoami) /usr/share/postgresql/12/extension/ /usr/lib/postgresql/12/lib/
-          sudo chown -R $(whoami) /usr/share/postgresql/13/extension/ /usr/lib/postgresql/13/lib/
-          sudo chown -R $(whoami) /usr/share/postgresql/14/extension/ /usr/lib/postgresql/14/lib/
-          sudo chown -R $(whoami) /usr/share/postgresql/15/extension/ /usr/lib/postgresql/15/lib/
+          sudo chown -R $(whoami) /usr/share/postgresql/${{ matrix.pg_version }}/extension/ /usr/lib/postgresql/${{ matrix.pg_version }}/lib/
+          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH
 
-          # Add PostgreSQL binaries to the PATH for integration tests
-          echo "/usr/lib/postgresql/11/bin" >> $GITHUB_PATH
-          echo "/usr/lib/postgresql/12/bin" >> $GITHUB_PATH
-          echo "/usr/lib/postgresql/13/bin" >> $GITHUB_PATH
-          echo "/usr/lib/postgresql/14/bin" >> $GITHUB_PATH
-          echo "/usr/lib/postgresql/15/bin" >> $GITHUB_PATH
-
-      # Check if cargo-pgrx, grcov, and llvm-tools-preview are in the cache, and install if not
       - name: Install pgrx, grcov & llvm-tools-preview
         working-directory: pg_bm25
         run: |
-          if ! command -v cargo-pgrx &> /dev/null; then
-            cargo install cargo-pgrx --version 0.9.8
-          fi
-          if ! command -v grcov &> /dev/null; then
-            cargo install grcov
-          fi
-          if ! rustup component list | grep -q 'llvm-tools-preview.*(installed)'; then
-            rustup component add llvm-tools-preview
-          fi
+          cargo install cargo-pgrx --version 0.9.8 || true
+          cargo install grcov || true
+          rustup component add llvm-tools-preview || true
 
-      - name: Initialize pgrx
+      - name: Initialize pgrx for Current PostgreSQL Version
         working-directory: pg_bm25
         run: |
-          cargo pgrx init \
-            --pg11=/usr/lib/postgresql/11/bin/pg_config \
-            --pg12=/usr/lib/postgresql/12/bin/pg_config \
-            --pg13=/usr/lib/postgresql/13/bin/pg_config \
-            --pg14=/usr/lib/postgresql/14/bin/pg_config \
-            --pg15=/usr/lib/postgresql/15/bin/pg_config
+          cargo pgrx init --pg${{ matrix.pg_version }}=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config
 
+      # The || true ensures that the step doesn't fail if the tool is already installed (i.e. in the cache)
       - name: Run pg_bm25 Unit Tests
         working-directory: pg_bm25
         run: |
@@ -114,4 +100,4 @@ jobs:
 
       - name: Run pg_bm25 Integration Tests
         working-directory: pg_bm25
-        run: ./test/runtests.sh
+        run: ./test/runtests.sh "${{ matrix.pg_version }}"
